export const HOME_CONFIGS = {
  categories: [
    {
      id: 1,
      createdAt: null,
      updatedAt: null,
      deletedAt: null,
      sortId: 1,
      title: 'Go incognito',
      desc: '',
      buttons: [
        {
          id: 1,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 1,
          sortId: 12,
          key: 'trade',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Trade%20Copy.png',
          title: 'Trade',
          desc: 'Buy crypto',
          route: 'Trade',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 2,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 1,
          sortId: 2,
          key: 'wallet',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/homeicons5/Assets.png',
          title: 'Manage',
          desc: 'Shield, send & receive',
          route: 'Wallet',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 6,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 1,
          sortId: 6,
          key: 'isssue_a_coin',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Mint.png',
          title: 'Mint',
          desc: 'Issue your own privacy coin',
          route: 'CreateToken',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
      ],
    },
    {
      id: 2,
      createdAt: null,
      updatedAt: null,
      deletedAt: null,
      sortId: 2,
      title: 'Power privacy',
      desc: '',
      buttons: [
        {
          id: 4,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 2,
          sortId: 5,
          key: 'stake_prv',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Pool.png',
          title: 'Stake',
          desc: 'Join a pool',
          route: 'Stake',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 5,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 2,
          sortId: 4,
          key: 'node',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Node22.png',
          title: 'Power',
          desc: 'Contribute liquidity',
          route: 'Node',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 7,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 2,
          sortId: 7,
          key: 'community',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Discussion.png',
          title: 'Connect',
          desc: 'Create conversations',
          route: 'Community',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 13,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 2,
          sortId: 1,
          key: 'invest',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/homeicons5/Invest.png',
          title: 'Invest',
          desc: 'Contribute liquidity',
          route: 'Dex',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 14,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 2,
          sortId: 10,
          key: 'pApp',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Browser.png',
          title: 'Browser',
          desc: '',
          route: 'pApp',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
      ],
    },
    {
      id: 3,
      createdAt: null,
      updatedAt: null,
      deletedAt: null,
      sortId: 3,
      title: 'More',
      desc: '',
      buttons: [
        {
          id: 10,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 3,
          sortId: 10,
          key: 'explorer',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Explorer.png',
          title: 'Explorer',
          desc: 'Discover the network',
          route: 'https://incscan.io/',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
        {
          id: 15,
          createdAt: '2020-04-27T04:17:27Z',
          updatedAt: '2020-04-27T04:17:27Z',
          deletedAt: null,
          appGroupId: 3,
          sortId: 8,
          key: 'setting',
          icoUrl:
            'https://storage.googleapis.com/incognito/wallet/icons/home-final/Settings.png',
          title: 'Settings',
          desc: 'Manager keys and preferences',
          route: 'Setting',
          message: '',
          toolTip: {
            id: 0,
            createdAt: null,
            updatedAt: null,
            deletedAt: null,
            appConfigId: 0,
            title: '',
            message: '',
          },
        },
      ],
    },
  ],
  headerTitle: 'Incognito mode\nfor your crypto',
};
