import TOKEN_DATA from './tokenData';

export default {
  // old varibles, maybe remove later
  CONST_SYMBOL: 'PRV',
  STAKING_TYPES: {
    SHARD: 0,
    BEACON: 1
  },
  STAKING_AMOUNT: 200,
  STAKING_MIN_FEE: 0.01,
  STAKING_ADDRESS: '1NHp2EKw7ALdXUzBfoRJvKrBBM9nkejyDcHVPvUjDcWRyG22dHHyiBKQGL1c',
  DEFRAGMENT_DEFAULT_AMOUNT: 1,
  DEFRAGMENT_MIN_FEE: 0.01,
  DEFRAGMENT_SET_DEFAULT_PRIVACY: true,

  MILICONSTANT_UNIT: 100,
  AMOUNT_CONSTANT_MIN: 0.01,
  AMOUNT_TOKEN_MIN: 0.01,
  INIT_TOKEN: 0,
  SEND_TOKEN: 1,
  NORMAL_TOKEN_TAB: 0,
  PRIVACY_TOKEN_TAB: 1,

  // for new app
  DECISION_RATE: {
    [TOKEN_DATA.SYMBOL.pETH]: 1e9,
    [TOKEN_DATA.SYMBOL.pBTC]: 1e9,
    [TOKEN_DATA.SYMBOL.MAIN_PRIVACY]: 1e2
  },
  TOKEN_TX_TYPE: {
    INIT: 0,
    SEND: 1
  },
  CURRENCY_TYPE_FOR_GEN_ADDRESS: {
    ETH: 1,
    BTC: 2 
  },
  ADDRESS_TYPE_FOR_GEN_ADDRESS: {
    DEPOSIT: 1,
    WITHDRAW: 2 
  }
};