export default {
  DEPOSIT : 'deposit',
  VIEW_SEND : 'view_send',
  SEND : 'send',
  SEND_SUCCESS : 'send_success',
  SEND_FAILED : 'send_failed',
  VIEW_WITHDRAW : 'view_withdraw',
  WITHDRAW : 'withdraw',
  WITHDRAW_SUCCESS : 'withdraw_success',
  WITHDRAW_FAILED : 'withdraw_failed',
  DEPOSIT_PDEX : 'deposit_pdex',
  DEPOSIT_PDEX_SUCCESS : 'deposit_pdex_success',
  DEPOSIT_PDEX_FAILED : 'deposit_pdex_failed',
  VIEW_TRADE: 'view_trade',
  TRADE : 'trade',
  TRADE_SUCCESS : 'trade_success',
  TRADE_FAILED : 'trade_failed',
  WITHDRAW_PDEX : 'withdraw_pdex',
  WITHDRAW_PDEX_SUCCESS : 'withdraw_pdex_success',
  WITHDRAW_PDEX_FAILED : 'withdraw_pdex_failed',
};
