export default {
  black: 'black',
  white: 'white',
  blue: '#0DB8D8',
  red: 'red',
  orange: 'orange',
  yellow: 'yellow',
  green: 'green',
  purple: 'purple',
  lightGrey: '#c2c2c2',
  lightGrey2: '#fafafa',
  transparent: 'transparent',
  overlayBlack: 'rgba(0, 0, 0, 0.5)',
  overlayBlackDark: 'rgba(0, 0, 0, 0.8)',
  overlayBlackLight: 'rgba(0, 0, 0, 0.3)',
  primary: '#007bff',
  blueLight: '#00D7FF',
  headerColor: '#263B41',
};