export default {
  RootApp: 'App',
  RootSplash: 'RootSplash',
  RootMiner: 'RootMiner',
  RootTab: 'RootTab',
  Home: 'Home',
  Setting: 'Setting',
  UserHeaderBoard: 'UserHeaderBoard',
  SendConstant: 'SendConstant',
  NetworkSetting: 'NetworkSetting',
  CreateAccount: 'CreateAccount',
  ImportAccount: 'ImportAccount',
  SeedPhrase: 'SeedPhrase',
  ExportAccount: 'ExportAccount',
  CreateSendToken: 'CreateSendToken',
  FollowToken: 'FollowToken',
  GetStarted: 'GetStarted',
  WalletDetail: 'WalletDetail',
  AddDevice: 'AddDevice',
  AddSelfNode: 'AddSelfNode',
  MineStack: 'MineStack',
  HomeStack: 'HomeStack',
  HomeMine: 'HomeMine',
  AddWallScreen: 'AddWallScreen',
  AddNode: 'AddNode',
  AddStake:'AddStake',
  Profile: 'Profile',
  ConfigDevice: 'ConfigDevice',
  DetailDevice: 'DetailDevice',
  SetupWifiDevice: 'SetupWifiDevice',
  MineSetting: 'MineSetting',
  ReceiveCrypto: 'ReceiveCrypto',
  SendCrypto: 'SendCrypto',
  Deposit: 'Deposit',
  Withdraw: 'Withdraw',
  CreateToken: 'CreateToken',
  Wizard: 'Wizard'
};
