export default {
  RootApp: 'App',
  RootSplash: 'Splash',
  RootSubscribeEmailNavigator: 'SubscribeEmailNavigator',
  RootAuth: 'Auth',
  Login: 'Login',
  Splash: 'Splash',
  Home: 'Home',
  Setting: 'Setting',
  CreatePassword: 'CreatePassword',
  UserHeaderBoard: 'UserHeaderBoard',
  SendConstant: 'SendConstant',
  Staking: 'Staking',
  Defragment: 'Defragment',
  NetworkSetting: 'NetworkSetting',
  CreateAccount: 'CreateAccount',
  ImportAccount: 'ImportAccount',
  SeedPhrase: 'SeedPhrase',
  ExportAccount: 'ExportAccount',
  CreateSendToken: 'CreateSendToken',
  FollowToken: 'FollowToken',
  HistoryToken: 'HistoryToken',
  GetStarted: 'GetStarted'
};