// Objective-C API for talking to github.com/incognitochain/incognito-chain/privacy/wasm/gomobile Go package.
//   gobind -lang=objc github.com/incognitochain/incognito-chain/privacy/wasm/gomobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long GomobileAdd(long a, long b);

/**
 * args {
     "values": valueStrs,
     "rands": randStrs
   }
convert object to JSON string (JSON.stringify)
 */
FOUNDATION_EXPORT NSString* _Nonnull GomobileAggregatedRangeProve(NSString* _Nullable args);

/**
 * GenerateBLSKeyPairFromSeed generates BLS key pair from seed
 */
FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateBLSKeyPairFromSeed(NSString* _Nullable args);

/**
 * args {
     "commitments": commitments,   // list of bytes arrays
     "rand": rand,					// string
		"indexiszero" 					//number
   }
convert object to JSON string (JSON.stringify)
 */
FOUNDATION_EXPORT NSString* _Nonnull GomobileOneOutOfManyProve(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileSayHello(NSString* _Nullable i);

#endif
