// Objective-C API for talking to github.com/incognitochain/incognito-chain/privacy/wasm/gomobile Go package.
//   gobind -lang=objc github.com/incognitochain/incognito-chain/privacy/wasm/gomobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long GomobileAdd(long a, long b);

FOUNDATION_EXPORT NSString* _Nonnull GomobileAggregatedRangeProve(NSString* _Nullable args);

FOUNDATION_EXPORT NSString* _Nonnull GomobileSayHello(NSString* _Nullable i);

#endif
