# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 6.3.0'
pod 'Firebase/Messaging', '~> 6.3.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge'
]

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Third party deps podspec link
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
pod 'RNSound', :path => '../node_modules/react-native-sound'
pod 'RNSensors', :path => '../node_modules/react-native-sensors'


target 'constantWalletMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for constantWalletMobile

  target 'constantWalletMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'react-native-udp', :path => '../node_modules/react-native-udp'

  end

  target 'constantWalletMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'constantWalletMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for constantWalletMobile-tvOS
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end
