# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 6.3.0'
pod 'Firebase/Messaging', '~> 6.3.0'

target 'constantWalletMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for constantWalletMobile

  target 'constantWalletMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'constantWalletMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'constantWalletMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for constantWalletMobile-tvOS
end
