import { genNamspace } from '@src/utils/reduxUtils';

const n = genNamspace('ACCOUNT');

// define types here
const TYPES = {
  SET: n('SET'),
  SET_LIST: n('SET_LIST'),
  REMOVE_BY_PRIVATE_KEY: n('REMOVE_BY_PRIVATE_KEY'),
  GET_BALANCE: n('GET_BALANCE'),
  GET_BALANCE_FINISH: n('GET_BALANCE_FINISH'),
  SET_DEFAULT_ACCOUNT: n('SET_DEFAULT_ACCOUNT'),
  ACTION_SWITCH_ACCOUNT_FETCHING: n('ACTION_SWITCH_ACCOUNT_FETCHING'),
  ACTION_SWITCH_ACCOUNT_FETCHED: n('ACTION_SWITCH_ACCOUNT_FETCHED'),
  ACTION_SWITCH_ACCOUNT_FETCH_FAIL: n('ACTION_SWITCH_ACCOUNT_FETCH_FAIL'),
  ACTION_FETCHING_CREATE_ACCOUNT: n('ACTION_FETCHING_CREATE_ACCOUNT'),
  ACTION_FETCHED_CREATE_ACCOUNT: n('ACTION_FETCHED_CREATE_ACCOUNT'),
  ACTION_FETCH_FAIL_CREATE_ACCOUNT: n('ACTION_FETCH_FAIL_CREATE_ACCOUNT'),
  ACTION_FETCHING_IMPORT_ACCOUNT: n('ACTION_FETCHING_IMPORT_ACCOUNT'),
  ACTION_FETCHED_IMPORT_ACCOUNT: n('ACTION_FETCHED_IMPORT_ACCOUNT'),
  ACTION_FETCH_FAIL_IMPORT_ACCOUNT: n('ACTION_FETCH_FAIL_IMPORT_ACCOUNT'),
  SET_SIGN_PUBLIC_KEY_ENCODE: n('SET_SIGN_PUBLIC_KEY_ENCODE'),
};

export default TYPES;
