import { genNamspace } from '@src/utils/reduxUtils';

const n = genNamspace('TOKEN');

// define types here
const TYPES = {
  SET: n('SET'),
  SET_BULK: n('SET_BULK'),
  GET_BALANCE: n('GET_BALANCE'),
  GET_BALANCE_FINISH: n('GET_BALANCE_FINISH'),
  REMOVE_BY_ID: n('REMOVE_BY_ID'),
  SET_LIST: n('SET_LIST'),
  SET_PTOKEN_LIST: n('SET_PTOKEN_LIST'),
  SET_INTERNAL_LIST: n('SET_INTERNAL_LIST'),
  ADD_FOLLOW_TOKEN_SUCCESS: n('ADD_FOLLOW_TOKEN_SUCCESS'),
  ADD_FOLLOW_TOKEN_FAIL: n('ADD_FOLLOW_TOKEN_FAIL'),
  ACTION_FETCHING_EXCHANGE_RATE: n('ACTION_FETCHING_EXCHANGE_RATE'),
  ACTION_FETCHED_EXCHANGE_RATE: n('ACTION_FETCHED_EXCHANGE_RATE'),
  ACTION_FETCH_FAIL_EXCHANGE_RATE: n('ACTION_FETCH_FAIL_EXCHANGE_RATE'),
  ACTION_FETCHING_HISTORY: n('ACTION_FETCHING_HISTORY'),
  ACTION_FETCHED_HISTORY: n('ACTION_FETCHED_HISTORY'),
  ACTION_FETCH_FAIL_HISTORY: n('ACTION_FETCH_FAIL_HISTORY'),
  ACTION_INIT_HISTORY: n('ACTION_INIT_HISTORY'),
};

export default TYPES;
